name: PHP Composer

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"

        coverage-driver:
          - "pcov"
          - "xdebug"
          - "xdebug3"

        exclude:
          - php-version: "8.0"
            coverage-driver: "xdebug"

    steps:
    - uses: actions/checkout@v2
    
    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: "${{ matrix.coverage-driver }}"
        
    - name: "Cache dependencies installed with composer"
      uses: "actions/cache@v2"
      with:
        path: "~/.composer/cache"
        key: "php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}"
        restore-keys: "php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: "Run tests with phpunit/phpunit"
      run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

    - name: "Send code coverage report to Codecov.io"
      env:
        CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
      run: "bash <(curl -s https://codecov.io/bash) || true"

